#!/usr/bin/env python3

import csv
import json
from pathlib import Path

from colorama import Fore, init

init(autoreset=True)

# ============================================================
# Interim Evaluation 2b - Computational Cost (Table 5)
#
# Does not rerun benchmarks. Reads benchmark JSON reports
# generated by run_interim_eval2.py, prints Table 5, and writes
# the Table 5 summary CSV.
# ============================================================

REPO_ROOT = Path(__file__).resolve().parents[2]
OUT_ROOT = (REPO_ROOT / "results" / "interim" / "eval2").resolve()
REPORTS_DIR = OUT_ROOT / "reports"
METRICS_DIR = OUT_ROOT / "metrics"
COST_SUMMARY_CSV = METRICS_DIR / "table_eval2_cost_summary.csv"

CONFIGS = [
    ("C1", 5, 0.85, "threshold-tuning-baseline-phash5-ssim085"),
    ("C2", 4, 0.85, "threshold-tuning-phash4-ssim085"),
    ("C3", 5, 0.90, "threshold-tuning-phash5-ssim090"),
    ("C4", 6, 0.85, "threshold-tuning-phash6-ssim085"),
    ("C5", 6, 0.90, "threshold-tuning-phash6-ssim090"),
]

COST_TABLE_COLUMNS = [
    ("ConfigID", "Config ID", 13, "left"),
    ("Stage1Time", "Stage 1 Time", 18, "center"),
    ("Stage2Time", "Stage 2 Time", 18, "center"),
    ("Stage3Time", "Stage 3 Time", 18, "center"),
    ("TotalTime", "Total Time", 18, "center"),
    ("PipelinePeakMemMB", "Peak RAM", 10, "center"),
    ("Stage2CandidatePairs", "S2 Pairs", 9, "center"),
    ("Stage3VerifiedPairs", "S3 Pairs", 9, "center"),
]

COST_CSV_FIELDS = [
    "ConfigID",
    "RunTag",
    "pHashThreshold",
    "SSIMThreshold",
    "Stage1TimeMsMean",
    "Stage1TimeMsStd",
    "Stage2TimeMsMean",
    "Stage2TimeMsStd",
    "Stage3TimeMsMean",
    "Stage3TimeMsStd",
    "TotalTimeMsMean",
    "TotalTimeMsStd",
    "PipelinePeakMemMB",
    "Stage2CandidatePairs",
    "Stage3VerifiedPairs",
    "BenchmarkJSON",
]


def number(value, decimal_places: int = 2) -> str:
    """Format a numeric JSON value for the report table."""
    try:
        return f"{float(value):.{decimal_places}f}"
    except (TypeError, ValueError):
        return ""


def parse_benchmark_cost(json_path: Path) -> dict:
    """Extract runtime, memory and pair counts for Table 5."""
    if not json_path.is_file():
        raise FileNotFoundError(
            f"Missing benchmark report: {json_path}\n"
            "Run services/dedupe-py/run_interim_eval2.py first."
        )

    data = json.loads(json_path.read_text(encoding="utf-8"))

    def get_value(*keys, default=""):
        current = data
        for key in keys:
            if not isinstance(current, dict) or key not in current:
                return default
            current = current[key]
        return current

    def stage_metric(stage: str, metric: str, statistic: str):
        return get_value("stages", stage, metric, statistic)

    parsed = {
        "Stage1TimeMsMean": number(stage_metric("stage1_sha256", "time_ms", "mean")),
        "Stage1TimeMsStd": number(stage_metric("stage1_sha256", "time_ms", "std_dev")),
        "Stage2TimeMsMean": number(stage_metric("stage2_phash", "time_ms", "mean")),
        "Stage2TimeMsStd": number(stage_metric("stage2_phash", "time_ms", "std_dev")),
        "Stage3TimeMsMean": number(stage_metric("stage3_ssim", "time_ms", "mean")),
        "Stage3TimeMsStd": number(stage_metric("stage3_ssim", "time_ms", "std_dev")),
        "TotalTimeMsMean": number(get_value("total_pipeline_time_ms", "mean")),
        "TotalTimeMsStd": number(get_value("total_pipeline_time_ms", "std_dev")),
        "PipelinePeakMemMB": number(get_value("total_pipeline_peak_ram_mb")),
        "Stage2CandidatePairs": get_value("detections", "stage2_candidate_pairs"),
        "Stage3VerifiedPairs": get_value("detections", "stage3_verified_pairs"),
    }

    missing = [key for key, value in parsed.items() if value == ""]
    if missing:
        raise ValueError(
            f"Missing Table 5 fields in {json_path}: " + ", ".join(missing)
        )

    return parsed


def format_table_cell(value, width: int, alignment: str) -> str:
    """Format one console table cell."""
    text = str(value)
    if alignment == "left":
        return text.ljust(width)
    if alignment == "right":
        return text.rjust(width)
    return text.center(width)


def table_separator() -> str:
    """Create the horizontal Table 5 border."""
    return (
        "+" + "+".join("-" * (width + 2) for _, _, width, _ in COST_TABLE_COLUMNS) + "+"
    )


def print_table_header() -> None:
    """Print the Table 5 title and headings."""
    header = (
        "| "
        + " | ".join(
            format_table_cell(label, width, alignment)
            for _, label, width, alignment in COST_TABLE_COLUMNS
        )
        + " |"
    )

    print(f"\n{Fore.GREEN}=== Interim Evaluation 2 Results ===")

    print(f"{Fore.GREEN}Computational Cost by Configuration")
    print(f"{Fore.BLUE}{table_separator()}")
    print(f"{Fore.CYAN}{header}")
    print(f"{Fore.BLUE}{table_separator()}")


def print_table_row(row: dict, row_index: int) -> None:
    """Print one configuration row without mutating CSV data."""
    display_row = {
        **row,
        "ConfigID": ("C1 (baseline)" if row["ConfigID"] == "C1" else row["ConfigID"]),
        "Stage1Time": (f"{row['Stage1TimeMsMean']} +/- {row['Stage1TimeMsStd']}"),
        "Stage2Time": (f"{row['Stage2TimeMsMean']} +/- {row['Stage2TimeMsStd']}"),
        "Stage3Time": (f"{row['Stage3TimeMsMean']} +/- {row['Stage3TimeMsStd']}"),
        "TotalTime": (f"{row['TotalTimeMsMean']} +/- {row['TotalTimeMsStd']}"),
    }

    line = (
        "| "
        + " | ".join(
            format_table_cell(display_row[key], width, alignment)
            for key, _, width, alignment in COST_TABLE_COLUMNS
        )
        + " |"
    )

    if row["ConfigID"] == "C1":
        colour = Fore.GREEN
    elif row_index % 2 == 0:
        colour = Fore.CYAN
    else:
        colour = Fore.WHITE

    print(f"{colour}{line}", flush=True)


def write_cost_summary(rows: list[dict]) -> None:
    """Write the report-ready Table 5 CSV."""
    METRICS_DIR.mkdir(parents=True, exist_ok=True)

    csv_rows = [
        {field: row.get(field, "") for field in COST_CSV_FIELDS} for row in rows
    ]

    with COST_SUMMARY_CSV.open("w", newline="", encoding="utf-8") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=COST_CSV_FIELDS)
        writer.writeheader()
        writer.writerows(csv_rows)


def main() -> None:
    cost_rows = []

    print_table_header()

    for row_index, (
        config_id,
        phash,
        ssim,
        run_tag,
    ) in enumerate(CONFIGS):
        benchmark_json = (REPORTS_DIR / f"{run_tag}.json").resolve()

        row = {
            "ConfigID": config_id,
            "RunTag": run_tag,
            "pHashThreshold": phash,
            "SSIMThreshold": ssim,
            **parse_benchmark_cost(benchmark_json),
            "BenchmarkJSON": benchmark_json.as_posix(),
        }

        cost_rows.append(row)
        print_table_row(row, row_index)

    print(f"{Fore.BLUE}{table_separator()}")
    write_cost_summary(cost_rows)

    print(f"\n{Fore.GREEN}Done.")
    print(f"{Fore.YELLOW}Cost summary: {Fore.CYAN}{COST_SUMMARY_CSV}")
    print(f"{Fore.YELLOW}Source reports: {Fore.CYAN}{REPORTS_DIR}")


if __name__ == "__main__":
    main()
